import Image from "next/image";
import type { Metadata } from "next";
import { Code, Headphones, Lightbulb, Mic } from "lucide-react";
import { Button } from "@/components/ui/button";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Podcasting 2.0",
  // description: "Generated by create next app",
};

export default function Home() {
  return (
    <>
      <div className="py-18 flex flex-col justify-center lg:py-36">
        <h1>
          <span className="font-bold">Podcasting 2.0</span>
          <br />
          <br />
          Making podcasting better for audiences, podcasters, and developers
        </h1>
      </div>
      <div>
        <div className="grid gap-8 md:grid-cols-3">
          <div className="flex flex-col items-start py-3">
            <Headphones size={48} />
            <h2 className="my-3 text-2xl">For audiences</h2>
            <p>
              Enjoy richer listening and viewing experiences! Podcasting 2.0
              lets you follow, engage with, support, and share podcasts more
              easily.
            </p>
            <Link href="/apps" className="mt-auto">
              <Button>Find a better app!</Button>
            </Link>
            {/* <LinkContainer to="/apps">
              <Button>Try a better podcast app!</Button>
            </LinkContainer> */}
          </div>
          <div className="flex flex-col items-start py-3">
            <Mic size={48} />

            <h2 className="my-3 text-2xl">For podcasters</h2>
            <p>
              Podcasting 2.0 offers the new Podcast Namespace to improve your
              podcast, grow your audience, and even monetize your show!
            </p>
            <Link href="/podcasters" className="mt-auto">
              <Button>Upgrade my podcast!</Button>
            </Link>

            {/* <LinkContainer to="/podcasters">
              <Button>Upgrade to Podcasting 2.0!</Button>
            </LinkContainer> */}
          </div>
          <div className="flex flex-col items-start py-3">
            <Code size={48} />

            <h2 className="my-3 text-2xl">For developers</h2>
            <p>
              Integrate an open, inclusive, always-free podcast catalog API and
              add Podcasting 2.0 features to your app. Make finding, following,
              and funding podcasts easier for your users!
            </p>
            <Link href="/podcast-namespace" className="mt-auto">
              <Button>Add the Podcast Namespace!</Button>
            </Link>
            {/* <LinkContainer to="/developers">
              <Button>Put Podcasting 2.0 in your app!</Button>
            </LinkContainer> */}
          </div>
          {/* <div className="col-span-full flex flex-col items-start py-3">
            <Lightbulb size={48} />

            <h2 className="my-3 text-2xl">For anyone with ideas</h2>
            <p>
              Integrate an open, inclusive, always-free podcast catalog API and
              add Podcasting 2.0 features to your app. Make finding, following,
              and funding podcasts easier for your users!
            </p>
            <Button className="mt-auto">Get involved!</Button>
          </div> */}
        </div>
      </div>
    </>
  );
}
