import Image from "next/image";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Podcasting 2.0",
  // description: "Generated by create next app",
};

export default function Home() {
  return (
    <main className="container flex max-w-lg flex-col justify-center gap-4">
      <div className="">
        <h1 className="text-2xl">Podcasting 2.0</h1>
      </div>
    </main>
  );
}
