import Image from "next/image";
import type { Metadata } from "next";
import { Code, Headphones, Mic } from "lucide-react";

export const metadata: Metadata = {
  title: "Podcasting 2.0",
  // description: "Generated by create next app",
};

export default function Home() {
  return (
    <>
      <div className="text-4xl py-24 lg:py-60 flex flex-col justify-center">
        <h1>
          Making podcasting better for audiences, podcasters, and developers.
          <br />
          <br />
          <span className="font-bold">This is Podcasting 2.0!</span>
        </h1>
      </div>
      <div>
        <div className="grid md:grid-cols-3 gap-8">
          <div className="py-3">
            <Headphones size={48} />
            <h2 className="my-3 text-2xl">For audiences</h2>
            <p>
              Enjoy richer listening and viewing experiences! Podcasting 2.0
              lets you follow, engage with, support, and share podcasts more
              easily.
            </p>
            {/* <LinkContainer to="/apps">
              <Button>Try a better podcast app!</Button>
            </LinkContainer> */}
          </div>
          <div className="py-3">
            <Mic size={48} />

            <h2 className="my-3 text-2xl">For podcasters</h2>
            <p>
              Podcasting 2.0 offers the new Podcast Namespace to improve your
              podcast, grow your audience, and even monetize your show!
            </p>
            {/* <LinkContainer to="/podcasters">
              <Button>Upgrade to Podcasting 2.0!</Button>
            </LinkContainer> */}
          </div>
          <div className="py-3">
            <Code size={48} />

            <h2 className="my-3 text-2xl">For developers</h2>
            <p>
              Integrate an open, inclusive, always-free podcast catalog API and
              add Podcasting 2.0 features to your app. Make finding, following,
              and funding podcasts easier for your users!
            </p>
            {/* <LinkContainer to="/developers">
              <Button>Put Podcasting 2.0 in your app!</Button>
            </LinkContainer> */}
          </div>
        </div>
      </div>
    </>
  );
}
