import type { Metadata } from "next";
import { Poppins } from "next/font/google";
// import { Footer } from "@/components/ui/Footer";
// import { Header } from "@/components/ui/Header";
import { PHProvider, PostHogPageview } from "@/components/PHProvider";
import { Suspense } from "react";
import { Footer, Layout, Navbar } from "nextra-theme-docs";
import { Banner, Head } from "nextra/components";
import { getPageMap } from "nextra/page-map";
import { cn } from "@/lib/utils";
import "../globals.css";
import "nextra-theme-docs/style.css";

const poppins = Poppins({
  weight: ["400", "600"],
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Podcasting 2.0",
  // description: "Generated by create next app",
};

const banner = <Banner storageKey="some-key">Nextra 4.0 is released 🎉</Banner>;
const navbar = (
  <Navbar
    logo={<b>Podcasting 2.0</b>}
    // ... Your additional navbar options
  />
);
const footer = <Footer>Maintained by Daniel J. Lewis.</Footer>;

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      // Not required, but good for SEO
      lang="en"
      // Required to be set
      dir="ltr"
      // Suggested by `next-themes` package https://github.com/pacocoursey/next-themes#with-app
      suppressHydrationWarning
      className={cn(poppins.className, "transition-colors")}
    >
      <Head
      // ... Your additional head options
      >
        {/* Your additional tags should be passed as `children` of `<Head>` element */}
      </Head>
      <Suspense>
        <PostHogPageview />
      </Suspense>
      <PHProvider>
        <body>
          <Layout
            // banner={banner}
            navbar={navbar}
            pageMap={await getPageMap()}
            docsRepositoryBase="https://github.com/shuding/nextra/tree/main/docs"
            footer={footer}
            // ... Your additional layout options
          >
                <div className="flex shrink grow overflow-hidden bg-gradient-to-br from-blue-50 to-transparent text-slate-800 dark:bg-slate-900 dark:from-blue-950/50 dark:text-slate-100">
    <main className="container mx-auto  p-4 lg:px-8">

            {children}
            </main>
            </div>
          </Layout>
        </body>
      </PHProvider>
    </html>
  );
}
